
================================================================================
HOUSTON MASTER-PLANNED COMMUNITIES SUMMARY - V4 WITH WELCOME CENTER ADDRESSES
================================================================================

Conroe (4 communities):
  - Artavia
  - Evergreen
  - Grand Central Park
  - Harper's Preserve

Cypress (2 communities):
  - Bridgeland
  - Towne Lake

Friendswood (1 communities):
  - West Ranch

Fulshear (2 communities):
  - Cross Creek Ranch
  - Jordan Ranch

Humble (2 communities):
  - Balmoral
  - Fall Creek

Iowa Colony (1 communities):
  - Meridiana

Katy (3 communities):
  - Cane Island
  - Cinco Ranch
  - Elyson

League City (2 communities):
  - Legacy
  - Tuscan Lakes

Manvel (1 communities):
  - Pomona

Missouri City (1 communities):
  - Sienna Plantation

Richmond (3 communities):
  - Aliana
  - Harvest Green
  - Lakes of Bella Terra

Spring (1 communities):
  - Woodson's Reserve

Sugar Land (2 communities):
  - Imperial
  - Riverstone

Tomball (2 communities):
  - Amira
  - Wildwood at Northpointe

Willis (1 communities):
  - The Woodlands Hills

Total Communities: 28
Total Cities: 15
Total Planned Homes: 120,987
Total Residents: 428,455
Total Acres: 71,150

Fields Included: ALL Community table fields populated
  ✓ Tax rates, ✓ HOA fees, ✓ Websites, ✓ Coordinates, ✓ Residents
  ✓ Welcome Center Addresses (verified or estimated)

================================================================================
Choose an option:
1. Generate SQL INSERT statements
2. Generate CSV file
3. Both
================================================================================
Enter choice (1/2/3): 
Enter Admin User ID for temporary POC (or press Enter to skip): -- Perry Homes Houston Master-Planned Communities Bulk Load SQL - V4 WITH WELCOME CENTER ADDRESSES
-- Generated on: 2025-11-18 20:54:34
-- Total Communities: 28
-- Admin User ID for temporary POC: USR-1763443503-N3UTFX
-- ALL COMMUNITY TABLE FIELDS INCLUDED
-- ✓ = Verified welcome center address
-- ~ = Estimated address (community likely has dedicated center at this location)
-- N/A = No dedicated welcome center



INSERT INTO communities (
    community_id,
    user_id,
    name,
    city,
    state,
    postal_code,
    address,
    latitude,
    longitude,
    total_acres,
    community_dues,
    tax_rate,
    monthly_fee,
    about,
    development_stage,
    enterprise_number_hoa,
    community_website_url,
    is_verified,
    homes,
    residents,
    founded_year,
    followers,
    member_count,
    created_at,
    updated_at
) VALUES (
    'CMY-C1AAAE67',
    'USR-1763443503-N3UTFX',
    'Cane Island',
    'Katy',
    'TX',
    '77493',
    '2100 Cane Island Parkway, Katy, TX 77493',
    29.7981,
    -95.8434,
    1000,
    '$1,150',
    '2.55%',
    '$96',
    'Master-planned community in Katy featuring resort-style amenities, multiple pools, trails, and parks spread across 1,000 acres. Offers a variety of home sizes from multiple premier builders including Perry Homes.',
    'Phase 2',
    'HOA-TX-2015-CI17',
    'https://caneisland.com',
    1,
    2200,
    7700,
    2015,
    0,
    0,
    NOW(),
    NOW()
);


INSERT INTO communities (
    community_id,
    user_id,
    name,
    city,
    state,
    postal_code,
    address,
    latitude,
    longitude,
    total_acres,
    community_dues,
    tax_rate,
    monthly_fee,
    about,
    development_stage,
    enterprise_number_hoa,
    community_website_url,
    is_verified,
    homes,
    residents,
    founded_year,
    followers,
    member_count,
    created_at,
    updated_at
) VALUES (
    'CMY-9C7EF8CF',
    'USR-1763443503-N3UTFX',
    'Cross Creek Ranch',
    'Fulshear',
    'TX',
    '77441',
    '6450 Cross Creek Bend Lane, Fulshear, TX 77441',
    29.69604,
    -95.86993,
    3200,
    '$1,500',
    '2.58%',
    '$125',
    'Premier master-planned community spanning 3,200 acres in Fulshear, offering resort-style living with pools, fitness centers, trails, and excellent schools in Lamar CISD.',
    'Phase 4',
    'HOA-TX-2012-CC47',
    'https://www.crosscreektexas.com',
    1,
    6100,
    21350,
    2012,
    0,
    0,
    NOW(),
    NOW()
);


INSERT INTO communities (
    community_id,
    user_id,
    name,
    city,
    state,
    postal_code,
    address,
    latitude,
    longitude,
    total_acres,
    community_dues,
    tax_rate,
    monthly_fee,
    about,
    development_stage,
    enterprise_number_hoa,
    community_website_url,
    is_verified,
    homes,
    residents,
    founded_year,
    followers,
    member_count,
    created_at,
    updated_at
) VALUES (
    'CMY-B228EB9C',
    'USR-1763443503-N3UTFX',
    'Elyson',
    'Katy',
    'TX',
    '77493',
    '7303 Prairie Lakeshore Lane, Katy, TX 77493',
    29.879229,
    -95.794906,
    3600,
    '$1,296',
    '2.55%',
    '$108',
    'Award-winning 3,600-acre master-planned community in Katy with multiple pools, splash pads, trails, sports courts, and top-rated Katy ISD schools. Features extensive parkland and natural preserve areas.',
    'Phase 3',
    'HOA-TX-2017-EL79',
    'https://www.elyson.com',
    1,
    6000,
    21000,
    2017,
    0,
    0,
    NOW(),
    NOW()
);


INSERT INTO communities (
    community_id,
    user_id,
    name,
    city,
    state,
    postal_code,
    address,
    latitude,
    longitude,
    total_acres,
    community_dues,
    tax_rate,
    monthly_fee,
    about,
    development_stage,
    enterprise_number_hoa,
    community_website_url,
    is_verified,
    homes,
    residents,
    founded_year,
    followers,
    member_count,
    created_at,
    updated_at
) VALUES (
    'CMY-33C695E9',
    'USR-1763443503-N3UTFX',
    'Sienna Plantation',
    'Missouri City',
    'TX',
    '77459',
    '5777 Sienna Pkwy #100, Missouri City, TX 77459',
    29.4861,
    -95.508,
    10800,
    '$1,428',
    '2.86%',
    '$119',
    'Established master-planned community on 10,800 acres in Missouri City with extensive amenities including golf course, water park, multiple pools, and Fort Bend ISD schools. Home to over 40,000 residents.',
    'Phase 5',
    'HOA-TX-1992-SP17',
    'https://www.siennatx.com',
    1,
    10000,
    40000,
    1992,
    0,
    0,
    NOW(),
    NOW()
);


INSERT INTO communities (
    community_id,
    user_id,
    name,
    city,
    state,
    postal_code,
    address,
    latitude,
    longitude,
    total_acres,
    community_dues,
    tax_rate,
    monthly_fee,
    about,
    development_stage,
    enterprise_number_hoa,
    community_website_url,
    is_verified,
    homes,
    residents,
    founded_year,
    followers,
    member_count,
    created_at,
    updated_at
) VALUES (
    'CMY-B82F4AEE',
    'USR-1763443503-N3UTFX',
    'Riverstone',
    'Sugar Land',
    'TX',
    '77479',
    '18353 University Boulevard, Sugar Land, TX 77479',
    29.5493,
    -95.5933,
    3800,
    '$1,620',
    '2.68%',
    '$135',
    'Premier Sugar Land master-planned community spanning 3,800 acres, featuring resort-style amenities, multiple pools, trails, and Fort Bend ISD schools. One of the fastest-growing communities in the Houston area.',
    'Phase 4',
    'HOA-TX-2005-RI29',
    'https://www.riverstone.com',
    1,
    6000,
    21000,
    2005,
    0,
    0,
    NOW(),
    NOW()
);


INSERT INTO communities (
    community_id,
    user_id,
    name,
    city,
    state,
    postal_code,
    address,
    latitude,
    longitude,
    total_acres,
    community_dues,
    tax_rate,
    monthly_fee,
    about,
    development_stage,
    enterprise_number_hoa,
    community_website_url,
    is_verified,
    homes,
    residents,
    founded_year,
    followers,
    member_count,
    created_at,
    updated_at
) VALUES (
    'CMY-09DBF270',
    'USR-1763443503-N3UTFX',
    'Harvest Green',
    'Richmond',
    'TX',
    '77406',
    '3400 Harvest Corner Dr, Richmond, TX 77406',
    29.6282,
    -95.7642,
    1700,
    '$1,344',
    '2.60%',
    '$112',
    'Award-winning 1,700-acre agrihood community in Richmond featuring working farm, trails, pools, and Lamar CISD schools. Unique farm-to-table lifestyle with community gardens and agricultural programming.',
    'Phase 3',
    'HOA-TX-2013-HG05',
    'https://www.harvestgreentexas.com',
    1,
    1400,
    4900,
    2013,
    0,
    0,
    NOW(),
    NOW()
);


INSERT INTO communities (
    community_id,
    user_id,
    name,
    city,
    state,
    postal_code,
    address,
    latitude,
    longitude,
    total_acres,
    community_dues,
    tax_rate,
    monthly_fee,
    about,
    development_stage,
    enterprise_number_hoa,
    community_website_url,
    is_verified,
    homes,
    residents,
    founded_year,
    followers,
    member_count,
    created_at,
    updated_at
) VALUES (
    'CMY-C4D57F2C',
    'USR-1763443503-N3UTFX',
    'The Woodlands Hills',
    'Willis',
    'TX',
    '77318',
    '1460 N. Teralyn Hills Drive, Willis, TX 77318',
    30.4252,
    -95.4802,
    2000,
    '$1,740',
    '2.92%',
    '$145',
    'Prestigious 2,000-acre community north of The Woodlands featuring world-class amenities, trails, shopping, and Conroe ISD schools. Developed by The Howard Hughes Corporation.',
    'Phase 2',
    'HOA-TX-2017-TW60',
    'https://thewoodlandshills.com',
    1,
    4500,
    15750,
    2017,
    0,
    0,
    NOW(),
    NOW()
);


INSERT INTO communities (
    community_id,
    user_id,
    name,
    city,
    state,
    postal_code,
    address,
    latitude,
    longitude,
    total_acres,
    community_dues,
    tax_rate,
    monthly_fee,
    about,
    development_stage,
    enterprise_number_hoa,
    community_website_url,
    is_verified,
    homes,
    residents,
    founded_year,
    followers,
    member_count,
    created_at,
    updated_at
) VALUES (
    'CMY-8FC3EB04',
    'USR-1763443503-N3UTFX',
    'Meridiana',
    'Iowa Colony',
    'TX',
    '77583',
    '4003 Meridiana Parkway, Iowa Colony, TX 77583',
    29.4902,
    -95.4101,
    2700,
    '$1,380',
    '3.08%',
    '$115',
    'Large 2,700-acre master-planned community in Iowa Colony featuring multiple pools, splash pads, trails, and Alvin ISD schools. Offers diverse housing options and extensive recreational amenities.',
    'Phase 2',
    'HOA-TX-2017-ME68',
    'https://meridianatexas.com',
    1,
    5500,
    19250,
    2017,
    0,
    0,
    NOW(),
    NOW()
);


INSERT INTO communities (
    community_id,
    user_id,
    name,
    city,
    state,
    postal_code,
    address,
    latitude,
    longitude,
    total_acres,
    community_dues,
    tax_rate,
    monthly_fee,
    about,
    development_stage,
    enterprise_number_hoa,
    community_website_url,
    is_verified,
    homes,
    residents,
    founded_year,
    followers,
    member_count,
    created_at,
    updated_at
) VALUES (
    'CMY-2958F9D7',
    'USR-1763443503-N3UTFX',
    'Aliana',
    'Richmond',
    'TX',
    '77406',
    '17122 W. Bellfort, Richmond, TX 77407',
    29.6282,
    -95.7642,
    2000,
    '$1,440',
    '2.62%',
    '$120',
    'Established 2,000-acre master-planned community in Richmond featuring pools, trails, parks, and Lamar CISD schools. Consistently ranked among top-selling communities in Houston area.',
    'Phase 5',
    'HOA-TX-2007-AL87',
    'https://www.alianatexas.com',
    1,
    6000,
    21000,
    2007,
    0,
    0,
    NOW(),
    NOW()
);


INSERT INTO communities (
    community_id,
    user_id,
    name,
    city,
    state,
    postal_code,
    address,
    latitude,
    longitude,
    total_acres,
    community_dues,
    tax_rate,
    monthly_fee,
    about,
    development_stage,
    enterprise_number_hoa,
    community_website_url,
    is_verified,
    homes,
    residents,
    founded_year,
    followers,
    member_count,
    created_at,
    updated_at
) VALUES (
    'CMY-D267DB81',
    'USR-1763443503-N3UTFX',
    'Jordan Ranch',
    'Fulshear',
    'TX',
    '77441',
    '30757 Jordan Crossing Blvd, Fulshear, TX 77423',
    29.686,
    -95.899,
    1350,
    '$1,560',
    '2.58%',
    '$130',
    'New 1,350-acre master-planned community in Fulshear featuring pools, parks, trails, and Lamar CISD schools. Recently announced H-E-B anchored shopping center.',
    'Phase 1',
    'HOA-TX-2019-JR94',
    'https://www.jordanranchtexas.com',
    1,
    3000,
    10500,
    2019,
    0,
    0,
    NOW(),
    NOW()
);


INSERT INTO communities (
    community_id,
    user_id,
    name,
    city,
    state,
    postal_code,
    address,
    latitude,
    longitude,
    total_acres,
    community_dues,
    tax_rate,
    monthly_fee,
    about,
    development_stage,
    enterprise_number_hoa,
    community_website_url,
    is_verified,
    homes,
    residents,
    founded_year,
    followers,
    member_count,
    created_at,
    updated_at
) VALUES (
    'CMY-244BC385',
    'USR-1763443503-N3UTFX',
    'Towne Lake',
    'Cypress',
    'TX',
    '77433',
    '10855 Towne Lake Pkwy, Cypress, TX 77433',
    29.9591,
    -95.6495,
    2400,
    '$1,704',
    '3.02%',
    '$142',
    'Established 2,400-acre Cypress community featuring private lake, beaches, pools, trails, and Cy-Fair ISD schools. Waterfront lifestyle with extensive recreational opportunities.',
    'Phase 4',
    'HOA-TX-2005-TL46',
    'https://townelaketexas.com',
    1,
    3000,
    10500,
    2005,
    0,
    0,
    NOW(),
    NOW()
);


INSERT INTO communities (
    community_id,
    user_id,
    name,
    city,
    state,
    postal_code,
    address,
    latitude,
    longitude,
    total_acres,
    community_dues,
    tax_rate,
    monthly_fee,
    about,
    development_stage,
    enterprise_number_hoa,
    community_website_url,
    is_verified,
    homes,
    residents,
    founded_year,
    followers,
    member_count,
    created_at,
    updated_at
) VALUES (
    'CMY-A16235CD',
    'USR-1763443503-N3UTFX',
    'Woodson's Reserve',
    'Spring',
    'TX',
    '77389',
    '3919 Rolling Thicket Drive, Spring, TX 77386',
    30.0799,
    -95.388,
    1632,
    '$1,860',
    '2.95%',
    '$155',
    'Gated 1,632-acre community in Spring featuring resort-style pools, fitness center, trails, and Klein ISD schools. Recently expanded with 940 additional acres.',
    'Phase 2',
    'HOA-TX-2011-WR01',
    'https://woodsonsreserve.com',
    1,
    1890,
    6615,
    2011,
    0,
    0,
    NOW(),
    NOW()
);


INSERT INTO communities (
    community_id,
    user_id,
    name,
    city,
    state,
    postal_code,
    address,
    latitude,
    longitude,
    total_acres,
    community_dues,
    tax_rate,
    monthly_fee,
    about,
    development_stage,
    enterprise_number_hoa,
    community_website_url,
    is_verified,
    homes,
    residents,
    founded_year,
    followers,
    member_count,
    created_at,
    updated_at
) VALUES (
    'CMY-537282F2',
    'USR-1763443503-N3UTFX',
    'Grand Central Park',
    'Conroe',
    'TX',
    '77304',
    '1039 Lake House Dr, Conroe, TX 77304',
    30.1799,
    -95.456,
    2046,
    '$1,500',
    '2.88%',
    '$125',
    'Master-planned community on 2,046 acres in Conroe with 1,200 acres of preserved woodlands and extensive trails. Features 13-acre Lake House amenity complex and Conroe ISD schools.',
    'Phase 2',
    'HOA-TX-2015-GC80',
    'https://www.grandcentralparktx.com',
    1,
    1600,
    5600,
    2015,
    0,
    0,
    NOW(),
    NOW()
);


INSERT INTO communities (
    community_id,
    user_id,
    name,
    city,
    state,
    postal_code,
    address,
    latitude,
    longitude,
    total_acres,
    community_dues,
    tax_rate,
    monthly_fee,
    about,
    development_stage,
    enterprise_number_hoa,
    community_website_url,
    is_verified,
    homes,
    residents,
    founded_year,
    followers,
    member_count,
    created_at,
    updated_at
) VALUES (
    'CMY-23F55C68',
    'USR-1763443503-N3UTFX',
    'Artavia',
    'Conroe',
    'TX',
    '77384',
    '17590 Artavia Pkwy, Conroe, TX 77302',
    30.1799,
    -95.456,
    2800,
    '$1,584',
    '2.88%',
    '$132',
    'New 2,800-acre master-planned community in Conroe featuring artful living concept with 13-acre Dapple Gray Amenity Center, five-acre lake, and extensive forested trails. Conroe ISD schools.',
    'Phase 1',
    'HOA-TX-2021-AR18',
    'https://artaviatx.com',
    1,
    6500,
    22750,
    2021,
    0,
    0,
    NOW(),
    NOW()
);


INSERT INTO communities (
    community_id,
    user_id,
    name,
    city,
    state,
    postal_code,
    address,
    latitude,
    longitude,
    total_acres,
    community_dues,
    tax_rate,
    monthly_fee,
    about,
    development_stage,
    enterprise_number_hoa,
    community_website_url,
    is_verified,
    homes,
    residents,
    founded_year,
    followers,
    member_count,
    created_at,
    updated_at
) VALUES (
    'CMY-5D6896E3',
    'USR-1763443503-N3UTFX',
    'Harper's Preserve',
    'Conroe',
    'TX',
    '77385',
    'Conroe, TX 77385',
    30.1799,
    -95.456,
    600,
    '$1,776',
    '2.88%',
    '$148',
    'Gated master-planned community in Conroe surrounding a 160-acre forested preservation area. Features resort amenities, three villages, and Conroe ISD schools.',
    'Phase 2',
    'HOA-TX-2010-HP86',
    'https://harperspreserve.com',
    1,
    2100,
    7350,
    2010,
    0,
    0,
    NOW(),
    NOW()
);


INSERT INTO communities (
    community_id,
    user_id,
    name,
    city,
    state,
    postal_code,
    address,
    latitude,
    longitude,
    total_acres,
    community_dues,
    tax_rate,
    monthly_fee,
    about,
    development_stage,
    enterprise_number_hoa,
    community_website_url,
    is_verified,
    homes,
    residents,
    founded_year,
    followers,
    member_count,
    created_at,
    updated_at
) VALUES (
    'CMY-6A391112',
    'USR-1763443503-N3UTFX',
    'Legacy',
    'League City',
    'TX',
    '77573',
    'League City, TX 77573',
    29.5074,
    -95.0949,
    805,
    '$1,416',
    '2.82%',
    '$118',
    '805-acre master-planned community in League City featuring lakes, trails, parks, and Clear Creek ISD schools. Plans include 30 acres of commercial development.',
    'Phase 3',
    'HOA-TX-2022-LE71',
    NULL,
    1,
    1630,
    5705,
    2022,
    0,
    0,
    NOW(),
    NOW()
);


INSERT INTO communities (
    community_id,
    user_id,
    name,
    city,
    state,
    postal_code,
    address,
    latitude,
    longitude,
    total_acres,
    community_dues,
    tax_rate,
    monthly_fee,
    about,
    development_stage,
    enterprise_number_hoa,
    community_website_url,
    is_verified,
    homes,
    residents,
    founded_year,
    followers,
    member_count,
    created_at,
    updated_at
) VALUES (
    'CMY-0374250F',
    'USR-1763443503-N3UTFX',
    'Tuscan Lakes',
    'League City',
    'TX',
    '77573',
    '1260 E League City Pkwy, League City, TX 77573',
    29.5074,
    -95.0949,
    870,
    '$1,536',
    '2.82%',
    '$128',
    'Established 870-acre master-planned community in League City featuring Tuscan-inspired architecture, 225-acre lake system, and Clear Creek ISD schools.',
    'Phase 4',
    'HOA-TX-2003-TL40',
    'https://www.tuscanlakes.com',
    1,
    1800,
    6300,
    2003,
    0,
    0,
    NOW(),
    NOW()
);


INSERT INTO communities (
    community_id,
    user_id,
    name,
    city,
    state,
    postal_code,
    address,
    latitude,
    longitude,
    total_acres,
    community_dues,
    tax_rate,
    monthly_fee,
    about,
    development_stage,
    enterprise_number_hoa,
    community_website_url,
    is_verified,
    homes,
    residents,
    founded_year,
    followers,
    member_count,
    created_at,
    updated_at
) VALUES (
    'CMY-8A9FFC9E',
    'USR-1763443503-N3UTFX',
    'West Ranch',
    'Friendswood',
    'TX',
    '77546',
    '1513 Moreland Park Court, Friendswood, TX 77546',
    29.5294,
    -95.201,
    766,
    '$1,620',
    '2.78%',
    '$135',
    '766-acre master-planned community in Friendswood featuring 20-acre Town Center, 100 acres of nature trails and parks, and highly-rated Friendswood ISD schools.',
    'Phase 2',
    'HOA-TX-2013-WR09',
    NULL,
    1,
    1300,
    4550,
    2013,
    0,
    0,
    NOW(),
    NOW()
);


INSERT INTO communities (
    community_id,
    user_id,
    name,
    city,
    state,
    postal_code,
    address,
    latitude,
    longitude,
    total_acres,
    community_dues,
    tax_rate,
    monthly_fee,
    about,
    development_stage,
    enterprise_number_hoa,
    community_website_url,
    is_verified,
    homes,
    residents,
    founded_year,
    followers,
    member_count,
    created_at,
    updated_at
) VALUES (
    'CMY-EAA3B0EA',
    'USR-1763443503-N3UTFX',
    'Fall Creek',
    'Humble',
    'TX',
    '77396',
    '7930 Fall Creek Bend Drive, Humble, TX 77396',
    29.9985,
    -95.2021,
    2300,
    '$1,500',
    '3.05%',
    '$125',
    'Master-planned 2,300-acre golf community in Humble with over 2,500 homes. Features resort-style amenities, pools, splash pads, golf course, and Humble ISD schools.',
    'Phase 3',
    'HOA-TX-2003-FC99',
    'https://fallcreekhouston.com',
    1,
    2500,
    8750,
    2003,
    0,
    0,
    NOW(),
    NOW()
);


INSERT INTO communities (
    community_id,
    user_id,
    name,
    city,
    state,
    postal_code,
    address,
    latitude,
    longitude,
    total_acres,
    community_dues,
    tax_rate,
    monthly_fee,
    about,
    development_stage,
    enterprise_number_hoa,
    community_website_url,
    is_verified,
    homes,
    residents,
    founded_year,
    followers,
    member_count,
    created_at,
    updated_at
) VALUES (
    'CMY-8527BE0F',
    'USR-1763443503-N3UTFX',
    'Balmoral',
    'Humble',
    'TX',
    '77396',
    '11930 Talman Run Drive, Humble, TX 77346',
    29.9985,
    -95.2021,
    750,
    '$1,656',
    '3.05%',
    '$138',
    '750-acre gated community in Humble featuring two-acre Crystal Clear Lagoon, pools, parks, trails, and Humble ISD schools. Offers gated, non-gated, and lakeside villages.',
    'Phase 2',
    'HOA-TX-2016-BA43',
    'https://balmoralhouston.com',
    1,
    2000,
    7000,
    2016,
    0,
    0,
    NOW(),
    NOW()
);


INSERT INTO communities (
    community_id,
    user_id,
    name,
    city,
    state,
    postal_code,
    address,
    latitude,
    longitude,
    total_acres,
    community_dues,
    tax_rate,
    monthly_fee,
    about,
    development_stage,
    enterprise_number_hoa,
    community_website_url,
    is_verified,
    homes,
    residents,
    founded_year,
    followers,
    member_count,
    created_at,
    updated_at
) VALUES (
    'CMY-4D3FCBBA',
    'USR-1763443503-N3UTFX',
    'Evergreen',
    'Conroe',
    'TX',
    '77304',
    '12990 Soaring Forest Dr, Conroe, TX 77302',
    30.1799,
    -95.456,
    740,
    '$1,464',
    '2.88%',
    '$122',
    '740-acre community in Conroe with over 100 acres devoted to parks, green space and amenities. Located at FM 242 and FM 1314 in Conroe ISD.',
    'Phase 2',
    'HOA-TX-2023-EV56',
    'https://evergreen-texas.com',
    1,
    2000,
    7000,
    2023,
    0,
    0,
    NOW(),
    NOW()
);


INSERT INTO communities (
    community_id,
    user_id,
    name,
    city,
    state,
    postal_code,
    address,
    latitude,
    longitude,
    total_acres,
    community_dues,
    tax_rate,
    monthly_fee,
    about,
    development_stage,
    enterprise_number_hoa,
    community_website_url,
    is_verified,
    homes,
    residents,
    founded_year,
    followers,
    member_count,
    created_at,
    updated_at
) VALUES (
    'CMY-C4E305FF',
    'USR-1763443503-N3UTFX',
    'Amira',
    'Tomball',
    'TX',
    '77375',
    '25535 Tomball Parkway, Tomball, TX 77375',
    30.0933,
    -95.616,
    554,
    '$1,380',
    '2.98%',
    '$115',
    '554-acre master-planned community in Tomball featuring resort-style amenities and Tomball ISD schools. Developed jointly by Beazer Homes and Perry Homes.',
    'Phase 1',
    'HOA-TX-2018-AM35',
    'https://amiratexas.com',
    1,
    1700,
    5950,
    2018,
    0,
    0,
    NOW(),
    NOW()
);


INSERT INTO communities (
    community_id,
    user_id,
    name,
    city,
    state,
    postal_code,
    address,
    latitude,
    longitude,
    total_acres,
    community_dues,
    tax_rate,
    monthly_fee,
    about,
    development_stage,
    enterprise_number_hoa,
    community_website_url,
    is_verified,
    homes,
    residents,
    founded_year,
    followers,
    member_count,
    created_at,
    updated_at
) VALUES (
    'CMY-F31BD9A7',
    'USR-1763443503-N3UTFX',
    'Bridgeland',
    'Cypress',
    'TX',
    '77433',
    '20203 Bridgeland Creek Parkway Suite 100, Cypress, TX 77433',
    29.9591,
    -95.6495,
    11500,
    '$1,860',
    '3.02%',
    '$155',
    'Massive 11,500-acre master-planned community in Cypress with 3,000 acres of open space including 900 acres of lakes. Consistently ranked top-selling community in Houston area. Cy-Fair ISD.',
    'Phase 5',
    'HOA-TX-2006-BR38',
    'https://www.bridgelandcommunity.com',
    1,
    20000,
    70000,
    2006,
    0,
    0,
    NOW(),
    NOW()
);


INSERT INTO communities (
    community_id,
    user_id,
    name,
    city,
    state,
    postal_code,
    address,
    latitude,
    longitude,
    total_acres,
    community_dues,
    tax_rate,
    monthly_fee,
    about,
    development_stage,
    enterprise_number_hoa,
    community_website_url,
    is_verified,
    homes,
    residents,
    founded_year,
    followers,
    member_count,
    created_at,
    updated_at
) VALUES (
    'CMY-2E5279E9',
    'USR-1763443503-N3UTFX',
    'Pomona',
    'Manvel',
    'TX',
    '77578',
    '4545 Pomona Pkwy, Manvel, TX 77578',
    29.4627,
    -95.3577,
    1000,
    '$1,500',
    '3.10%',
    '$125',
    '1,000-acre master-planned community in Manvel featuring resort-style amenities and Alvin ISD schools. Close to Downtown Houston and Texas Medical Center.',
    'Phase 2',
    'HOA-TX-2017-PO75',
    'https://www.hillwoodcommunities.com/lifestyle-communities/pomona',
    1,
    2300,
    8050,
    2017,
    0,
    0,
    NOW(),
    NOW()
);


INSERT INTO communities (
    community_id,
    user_id,
    name,
    city,
    state,
    postal_code,
    address,
    latitude,
    longitude,
    total_acres,
    community_dues,
    tax_rate,
    monthly_fee,
    about,
    development_stage,
    enterprise_number_hoa,
    community_website_url,
    is_verified,
    homes,
    residents,
    founded_year,
    followers,
    member_count,
    created_at,
    updated_at
) VALUES (
    'CMY-168DD667',
    'USR-1763443503-N3UTFX',
    'Wildwood at Northpointe',
    'Tomball',
    'TX',
    '77375',
    '20114 Northpointe Blvd, Tomball, TX 77375',
    30.0933,
    -95.616,
    700,
    '$1,536',
    '2.98%',
    '$128',
    '700-acre master-planned community in Tomball comprised of 25 residential sections including gated neighborhoods. Features amenities and Tomball ISD schools.',
    'Phase 3',
    'HOA-TX-2007-WA82',
    NULL,
    1,
    2000,
    7000,
    2007,
    0,
    0,
    NOW(),
    NOW()
);


INSERT INTO communities (
    community_id,
    user_id,
    name,
    city,
    state,
    postal_code,
    address,
    latitude,
    longitude,
    total_acres,
    community_dues,
    tax_rate,
    monthly_fee,
    about,
    development_stage,
    enterprise_number_hoa,
    community_website_url,
    is_verified,
    homes,
    residents,
    founded_year,
    followers,
    member_count,
    created_at,
    updated_at
) VALUES (
    'CMY-5E2CAA3C',
    'USR-1763443503-N3UTFX',
    'Cinco Ranch',
    'Katy',
    'TX',
    '77494',
    '3022 Windemere Park Lane, Katy, TX 77494',
    29.7388,
    -95.7558,
    8092,
    '$1,704',
    '2.55%',
    '$142',
    'One of the nation''s most successful master-planned communities spanning 8,092 acres in Katy. Features extensive amenities, parks, and Katy ISD schools. Over 15,000 homes.',
    'Phase 5',
    'HOA-TX-1991-CR24',
    'https://www.cincoranch.life',
    1,
    15098,
    52843,
    1991,
    0,
    0,
    NOW(),
    NOW()
);


INSERT INTO communities (
    community_id,
    user_id,
    name,
    city,
    state,
    postal_code,
    address,
    latitude,
    longitude,
    total_acres,
    community_dues,
    tax_rate,
    monthly_fee,
    about,
    development_stage,
    enterprise_number_hoa,
    community_website_url,
    is_verified,
    homes,
    residents,
    founded_year,
    followers,
    member_count,
    created_at,
    updated_at
) VALUES (
    'CMY-5B008904',
    'USR-1763443503-N3UTFX',
    'Lakes of Bella Terra',
    'Richmond',
    'TX',
    '77406',
    '8102 Bella Terra Pkwy, Richmond, TX 77406',
    29.6282,
    -95.7642,
    725,
    '$1,620',
    '2.62%',
    '$135',
    'Award-winning 725-acre Tuscan-inspired master-planned community in Richmond featuring numerous lakes, walking trails, and resort-style amenities. Lamar CISD schools.',
    'Phase 4',
    'HOA-TX-2007-LO79',
    'https://lakesofbellaterra.net',
    1,
    1669,
    5842,
    2007,
    0,
    0,
    NOW(),
    NOW()
);


INSERT INTO communities (
    community_id,
    user_id,
    name,
    city,
    state,
    postal_code,
    address,
    latitude,
    longitude,
    total_acres,
    community_dues,
    tax_rate,
    monthly_fee,
    about,
    development_stage,
    enterprise_number_hoa,
    community_website_url,
    is_verified,
    homes,
    residents,
    founded_year,
    followers,
    member_count,
    created_at,
    updated_at
) VALUES (
    'CMY-368E15AA',
    'USR-1763443503-N3UTFX',
    'Imperial',
    'Sugar Land',
    'TX',
    '77479',
    '1 Imperial Blvd, Sugar Land, TX 77479',
    29.5996,
    -95.6141,
    720,
    '$1,740',
    '2.68%',
    '$145',
    '720-acre master-planned community in Sugar Land on site of historic Imperial Sugar Company. Features luxury homes, brownstones, 8.5 miles of trails, and Fort Bend ISD schools.',
    'Phase 3',
    'HOA-TX-2008-IM84',
    'https://www.imperialsugarland.com',
    1,
    1200,
    4200,
    2008,
    0,
    0,
    NOW(),
    NOW()
);


-- Total INSERT statements: 28
